### ISSUE TITLE
Dynamic text support?

### ISSUE THREAD

**Issue by fallenartist** [LettError/responsiveLettering#24]
Amazing project 👍 I was wondering if it could support dynamically generated text? In theory, with path code for all characters in the four needed sizes in memory, a dynamic SVG could be assembled on the fly and HTML element updated. Have you tried that and can I add it as a feature request?

**Comment by LettError** [comment]
Cheers! In theory this is of course possible. You'd need to have a source for interpolatable outlines. A UFO? Specially prepared TTF?, read the data, construct the glyphs, interpolate and draw. That's quite some work for javascript if it has to happen in the client.
- Andrew Johnson [wrote about this](http://alistapart.com/article/live-font-interpolation-on-the-web) and has a working prototype, though I think it is a single glyph.
- If all the work can happen on the server it could use [MutatorMath](https://github.com/LettError/MutatorMath). [PhotoLettering uses it.](http://www.photolettering.com/a/4i3h1d0ba)
- If it can happen in a nice OSX app you could use [Superpolator](http://new.superpolator.com).

Will it ever be a feature of this specific project? Probably not.
